### ISSUE TITLE
npm run dev & npm run build problem

### ISSUE THREAD

**Issue by masonlin** [raineroviir/react-redux-socketio-chat#21]
I suffer some problems, when I step in $npm run dev or $npm run build,
the console reply the below log:

$npm run dev 
==================================
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev React-redux-socketio-chat@0.3.0
6 info dev React-redux-socketio-chat@0.3.0
7 verbose unsafe-perm in lifecycle true
8 info React-redux-socketio-chat@0.3.0 Failed to exec dev script
9 verbose stack Error: React-redux-socketio-chat@0.3.0 dev: `NODE_ENV=development node devServer`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid React-redux-socketio-chat@0.3.0
11 verbose cwd D:\Git\repositories\react-redux-socketio-chat-master
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error React-redux-socketio-chat@0.3.0 dev: `NODE_ENV=development node devServer`
17 error Exit status 1
18 error Failed at the React-redux-socketio-chat@0.3.0 dev script 'NODE_ENV=development node devServer'.
18 error This is most likely a problem with the React-redux-socketio-chat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=development node devServer
18 error You can get their info via:
18 error     npm owner ls React-redux-socketio-chat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

$npm run build
==================================
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild React-redux-socketio-chat@0.3.0
6 info build React-redux-socketio-chat@0.3.0
7 verbose unsafe-perm in lifecycle true
8 info React-redux-socketio-chat@0.3.0 Failed to exec build script
9 verbose stack Error: React-redux-socketio-chat@0.3.0 build: `npm run clean && npm run build:webpack`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid React-redux-socketio-chat@0.3.0
11 verbose cwd D:\Git\repositories\react-redux-socketio-chat-master
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error React-redux-socketio-chat@0.3.0 build: `npm run clean && npm run build:webpack`
17 error Exit status 1
18 error Failed at the React-redux-socketio-chat@0.3.0 build script 'npm run clean && npm run build:webpack'.
18 error This is most likely a problem with the React-redux-socketio-chat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run clean && npm run build:webpack
18 error You can get their info via:
18 error     npm owner ls React-redux-socketio-chat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

==================================
Could you please give me some suggestion?
Thank you very much.

**Comment by raineroviir** [comment]
I did a brief search, and from what I gather both your errors have to do with your OS being unable to set ENV variables properly. 
please look in this thread, they have similar issues and solutions: https://github.com/gpbl/isomorphic500/issues/40

**Comment by masonlin** [comment]
I modify the 2 sentence to solve this issue, Windows envirement variable issue must use "set" and "&&" to merge the commnds. 

=====================================
"dev": "NODE_ENV=development node devServer",
"dev": "set NODE_ENV=development && node devServer",
"build:webpack": "NODE_ENV=production webpack --config webpack.config.prod.js",
"build:webpack": "set NODE_ENV=production && webpack --config webpack.config.prod.js",

=====================================
Thanks for your infomation.

**Comment by raineroviir** [comment]
Glad to help!
