### ISSUE TITLE
History not in package.json

### ISSUE THREAD

**Issue by BrianGuo** [raineroviir/react-redux-socketio-chat#50]
I ran npm install, followed all the directions, and then tried to run 
```
npm run dev
```

However, I received an error in my console saying "cannot find module 'history'".
I looked in my node_modules directory and similarly, could not find history. 
I then ran "npm install history" and everything worked fine after that.
I looked in package.json and noticed that history is indeed not one of the required dependencies.
I don't know how it might have been overlooked, but I do think it should be there.

**Comment by BrianGuo** [comment]
update: this change will likely produce the error
```
TypeError: (0 , _history.createLocation) is not a function
   at server.dev.js:58:20
```

I fixed this issue by importing createLocation from history/lib/LocationUtils as opposed to just 'history'.

**Comment by raineroviir** [comment]
Yeah the way react router works with it splitting off history as a separate package and I haven't had time to update this project for a bit now.  I'm glad you were able to fix your own error, I'll close the issue
