### ISSUE TITLE
Question: how are sockets protected?

### ISSUE THREAD

**Issue by Nepoxx** [raineroviir/react-redux-socketio-chat#52]
I can't figure out from the code how the user's WebSocket is authenticated. I don't see [any authentication checks during the socket connection](https://github.com/raineroviir/react-redux-socketio-chat/blob/master/src/server/socketEvents.js#L2)

Am I missing something?

**Comment by raineroviir** [comment]
I haven't implemented auth on the sockets

**Comment by Nepoxx** [comment]
I'll look into it.
