### ISSUE TITLE
How to navigate to default Channel

### ISSUE THREAD

**Issue by swimhiking** [raineroviir/react-redux-socketio-chat#55]
I play around this application, create a new channel, then I found I am not able to back Lobby channel because it's not in the channels list; So in the reducers\activeChannel.js I added a console.log (state), then founded that Lobby channel has id of 0, others has a long string which means from MongoDB, of course I can just create a channel called "Lobby", I can navigate to default channel, but feeling not the right way; I wish Lobby channel is default in Channels list.

**Comment by raineroviir** [comment]
Hey,

Yeah that little quirk is a shortcut I took, I don't have the time right now to implement the correct fix but It's probably a useful exercise to learn something if you'd like to do it yourself :)

Best,

**Comment by raineroviir** [comment]
I made it so Lobby is by default part of every new User, so it will be a default channel in the channel list
https://github.com/raineroviir/react-redux-socketio-chat/commit/2dc52e7bdda095448856d2dfea599215f8dfbc3e
